learning_templates/app1/urls.py
from app1 import views
from django.conf.urls import url

#TEMPLATE TAGGING

app_name = "app1"

urlpatterns = [
    url(r'^other',views.other,name="other"),
    url(r'^relative',views.relative,name="relative"),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app1 import views

urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^app1/', include("app1.urls")),
]

learning_templates/app1/models.py
from django.db import models

# Create your models here.

learning_templates/app1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context = {'text':'Hello World','number':100}
    return render(request,'app1/index.html',context)

def other(request):
    return render(request,'app1/other.html')

def relative(request):
    return render(request,'app1/relative_url_templates.html')

learning_templates/app1/templates/app1/app1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    
    <nav class="navbar navbar-default navbar-static-top" >   
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url "index"%}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url "admin:index"%}">Admin</a></li>
                <li><a class="navbar-link" href="{% url "app1:other"%}">Other</a></li>    
            </ul>
        </div>
    </nav>
    
    <div class="container">
        {% block body_block%}
        <!--Heritage -->
        {% endblock %}
    </div>
    
</body>
</html>

learning_templates/app1/templates/app1/index.html
<!DOCTYPE html>
{% extends "app1/app1.html"%}
{% load scripts %}
    {% block body_block%}
        <h1>WELCOME TO THE INDEX PAGE</h1>
        <h2>This is the index.html showing the page</h2>
        <h1>{{ text|cut:'World' }} </h1>
        <h2>{{number|add:"-10"}}</h2>
    {% endblock %}

learning_templates/app1/templates/app1/other.html
<!DOCTYPE html>
{% extends "app1/app1.html" %}

{% block body_block%}
    <h1>WELCOME TO THE OTHER PAGE</h1>
    <h2>Ceci est une exemple d un heritage de template </h2>
{% endblock %}

learning_templates/app1/templates/app1/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO THE RELATIVE URL PAGE</h1>
    <a href="{% url "app1:other"%}"> Go to Other Pages </a><br>
    <a href="{% url "admin:index"%}"> Go to Administration Page </a><br>
    <a href="{% url "index"%}"> Go to Index page of the internet Sites </a><br>
</body>
</html>